try:
    result=45/0
except:
    print("Error happend")
finally:
    print("Finally happend")

print("Done")